{
  pkgs,
  lib,
  unstable,
  vpngate,
  ...
}:
let
  inherit (pkgs) stdenv;
in
{
  environment.systemPackages =
    with pkgs;
    [
      atuin
      bat
      btop
      curl
      doggo
      dust
      eza
      fd
      github-cli
      gnumake
      gnupg
      just
      jq
      lsof
      macchina
      ncdu
      nil
      nix-tree
      nixd
      nixfmt
      bash-language-server
      yaml-language-server
      nvd
      progress
      ripgrep
      shellcheck
      shfmt
      terraform-ls
      unstable.krew
      unstable.kubecolor
      unstable.kubectl
      unstable.kubectx
      unstable.kubectl-tree
      unstable.kubernetes-helm
      unstable.stern
      unzip
      viddy
      virtualenv
      yq-go
      zip
    ]
    ++ lib.optionals stdenv.isLinux [
      arp-scan
      cliphist
      cryptsetup
      dnsutils
      hardinfo2
      iperf
      iputils
      libsecret
      remmina
      nfs-utils
      nmap
      openssl
      openvpn
      pciutils
      socat
      qemu
      tcpdump
      traceroute
      unstable.beszel
      usbutils
      vpngate.packages.${pkgs.stdenv.hostPlatform.system}.default
      whois
      wl-clip-persist
    ];
}
