{
  pkgs,
  lib,
  unstable,
  vpngate,
  ...
}:
let
  inherit (pkgs) stdenv;
in
{
  environment.systemPackages =
    with pkgs;
    [
      atuin
      bat
      btop
      cd-fzf
      curl
      doggo
      eza
      fd
      github-cli
      gnumake
      gnupg
      gofumpt
      golangci-lint
      gopls
      hadolint
      jq
      lsof
      macchina
      ncdu
      nil
      nix-tree
      nixd
      nixfmt-rfc-style
      nixpkgs-review
      nodePackages.bash-language-server
      nodePackages.eslint
      nodePackages.yaml-language-server
      nvd
      progress
      ripgrep
      rustup
      shellcheck
      shfmt
      terraform-ls
      unstable.krew
      unstable.kubecolor
      unstable.kubectl
      unstable.kubectx
      unstable.kubectl-tree
      unstable.kubernetes-helm
      unstable.stern
      unzip
      viddy
      virtualenv
      yq-go
      subtui
      yt-dlp
      zip
    ]
    ++ lib.optionals stdenv.isLinux [
      arp-scan
      bun
      cliphist
      cryptsetup
      dnsutils
      hardinfo2
      iperf
      iputils
      libsecret
      nfs-utils
      nmap
      openssl
      openvpn
      pciutils
      qemu
      tcpdump
      traceroute
      unrar
      unstable.beszel
      unstable.tailscale
      usbutils
      vpngate.packages.${pkgs.stdenv.hostPlatform.system}.default
      whois
      wl-clip-persist
    ];
}
