---
feeds:
- https://news.ycombinator.com/rss
- https://www.bleepingcomputer.com/feed/
- https://www.theregister.com/security/headlines.atom
- https://www.zdnet.com/topic/security/rss.xml
- https://www.cbc.ca/cmlink/rss-topstories
# Optionally define an application to view the feeds
externalViewer: brave
