name: "Build and push to cachix"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "*.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "*.md"
      - "LICENSE"
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31
      - run: nix fmt -- --check .
      - run: nix develop -c deadnix --fail .
      - run: nix develop -c statix check .
      - run: nix develop -c shellcheck $(git ls-files '*.sh')

  build-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        host:
          - helios
          - kratos
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: davegallant
          authToken: "${{ secrets.CACHIX_API_KEY }}"
      - run: nix build .#darwinConfigurations.${{ matrix.host }}.config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | cachix push davegallant

  build-hephaestus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: davegallant
          authToken: "${{ secrets.CACHIX_API_KEY }}"
      - run: nix build .#nixosConfigurations.hephaestus.config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | cachix push davegallant
