name: "Build and push to cachix"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '*.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - run: nix fmt -- --check .

  eval-kratos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - run: nix eval .#nixosConfigurations.kratos.config.system.build.toplevel --raw

  build-zelus:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - run: nix build .#darwinConfigurations.zelus.config.system.build.toplevel

  build-hephaestus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v17
      with:
        name: davegallant
        authToken: '${{ secrets.CACHIX_API_KEY }}'
    - run: nix build .#nixosConfigurations.hephaestus.config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | cachix push davegallant
