name: "Build and push to cachix"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '*.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v17
      with:
        name: davegallant
        authToken: '${{ secrets.CACHIX_API_KEY }}'
    - run: nix build .#nixosConfigurations.hephaestus.config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | cachix push davegallant
