name: "Build and push to cachix"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '*.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: davegallant
        authToken: '${{ secrets.CACHIX_API_KEY }}'
    - run: nix-build | cachix push davegallant
